# site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: http://localhost:4000/ # the base hostname & protocol for your site
languages: ["en", "hu", "it"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  hu: Magyar
  en: English
  it: Italiano
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:

# build settings
markdown: kramdown

sass:
  style: compressed


plugins:
      - jekyll-multiple-languages-plugin

#title: Dominic
#subtitle:  Professional Translator
#email: abacd@gef.com
#description: A great site for a great translator
#baseurl: "" # the subpath of your site, e.g. /blog
#url: # the base hostname & protocol for your site
#author:
#street_address: 1234 Somewhere Road
#city: Nashville
#state: TN
#zip_code: 55555
#country: United States of America
#phone: (716) 555-5555

